### ISSUE TITLE
HelmReques创建成功后，怎么查看具体创建了哪些k8s的资源？

### ISSUE THREAD

**Issue by yanh0606** [alauda/captain#116]
当前HelmReques创建成功后，并没有生成helm的实例，无法通过helm命令管理，那么HelmReques将chart包中包含的pod、pvc、svc等资源创建成功后，如何查看这个HelmReques具体创建了哪些k8s的资源呢？

**Comment by zhhray** [comment]
> 当前HelmReques创建成功后，并没有生成helm的实例，无法通过helm命令管理，那么HelmReques将chart包中包含的pod、pvc、svc等资源创建成功后，如何查看这个HelmReques具体创建了哪些k8s的资源呢？

1. helmrequest是基于k8s的crd + controller 的实现方式完成chart部署的，因此helmrequest产生的release是无法被helm命令管理的。
2. helmrequest生成的实例，会存储在release.app.alauda.io的cr中。因此，可以通过kubectl获取release.app.alauda.io的cr yaml内容，可以看到被部署的资源文件内容以及hook资源文件内容。可以参考[这里](https://github.com/alauda/captain/blob/master/docs/zh/crds/release.md#%E5%85%B3%E4%BA%8Erelease%E8%B5%84%E6%BA%90%E9%85%8D%E7%BD%AE%E7%BB%93%E6%9E%84)
3. 转换编码和压缩后的文本内容为可读性文本，可参考该命令：`echo "xxxxx" | base64 -d | gzip -d`
