### ISSUE TITLE
删除hr时报错

### ISSUE THREAD

**Issue by Gitttttttt** [alauda/captain#126]
首先我创建了一个hr资源文件（3-install-vela-core.yaml）用于安装vela：
![image](https://github.com/alauda/captain/assets/38375081/0c63efbe-23d6-414f-ac83-d97d0f776bab)

可以看到这个文件于四天前执行并且成功了：
![image](https://github.com/alauda/captain/assets/38375081/452e041e-b813-46df-823d-9b0ae50ab3dc)

现在我想要根据yaml删除安装的vela，于是报错了：
![image](https://github.com/alauda/captain/assets/38375081/d1948276-7eab-4aa4-af49-ae2cfe2df55a)
查看了deploy的状态也是正常的：
![image](https://github.com/alauda/captain/assets/38375081/1e4eace0-8560-4c46-b86e-8ae208f8b0a0)

多次尝试删除也是同样的错，于是我再次apply该文件，并且显示创建成功了，但pod和deploy还是4天前创建的那个：
![image](https://github.com/alauda/captain/assets/38375081/2bbdb0cc-163e-483a-ba6c-b8e30c9ff6a8)

然后再次尝试删除，成功了。。
![image](https://github.com/alauda/captain/assets/38375081/fcecea7e-9c6a-44bc-9f8d-18d95f97a58f)

虽然pod和deploy被删除了，但hr任然存在，这会导致从java端通过apply安装vela-core时报错：
![image](https://github.com/alauda/captain/assets/38375081/13a6c552-f0c3-4d4e-bc59-ebae88892c90)
![image](https://github.com/alauda/captain/assets/38375081/6ae68139-58e5-4a0a-b479-4d7f3b1e5177)

**Comment by Gitttttttt** [comment]
貌似只能通过删除相应的crd以删除pod，不能通过delete -f yaml删除

**Comment by zhhray** [comment]
1. 首先看到你apply的hr 并没有指定namespace，你是预期将Helmrequest资源部署到default ns下的吗？
2. 其次，理论上，当你创建Helmrequest资源时，captain会对该Helmrequest 指定的chart执行install/upgrade，当你删除Helmrequest资源时，captain会卸载（从集群中删除）之前安装过的资源。
3. 通过上述的步骤，如果问题还一直复现，可以留下联系方式，有空了一起远程看看。

**Comment by Gitttttttt** [comment]
我再次测试删除时，以上问题都不存在了，yaml文件还是原来那个，目前还不知道怎么复现-_-|||

**Comment by Gitttttttt** [comment]
但我疑惑的是，metadata.namespace定义了hr的命名空间，spec.namespace定义了deploy的命名空间，spec.namespace的存在会不会有点多余了？因为如果hr和deploy不在同一ns下，那管理起来还是麻烦了点，或者有什么特殊的用法吗？
![image](https://github.com/alauda/captain/assets/38375081/6cdb44a3-cb2c-40ab-b76f-45dfd1076342)

**Comment by zhhray** [comment]
是的没错。
metadata.namespace决定了hr资源被部署的目标命名空间。
spec.namespace决定了chart资源被部署的命名空间。
它们本身就是如此设计的，当spec.namespace没有指定时，默认会将chart资源部署到hr所在的命名空间里。
针对不同的使用场景，用法有所差异。
因此，建议在创建hr资源时，在hr的yaml种指定metadata.namespace。
