### ISSUE TITLE
通过hr安装vela-core异常

### ISSUE THREAD

**Issue by Gitttttttt** [alauda/captain#127]
1.我的HelmRequest如下所示：
![image](https://github.com/alauda/captain/assets/38375081/3e8c816b-fa6d-460d-bf46-55443e0da0a1)

2.如果部署成功，将会创建如下pod（这是之前通过hr成功创建的结果）：
![image](https://github.com/alauda/captain/assets/38375081/fe93face-fe74-43d3-b8f1-07300c5025b4)

3.但是现在执行了hr后，得到的却是如下的pod，并且一直创建不成功:
![image](https://github.com/alauda/captain/assets/38375081/5debd89f-b3fa-402d-891d-b0a4f2723239)

4.查看captain-controller-manager日志如下：
![image](https://github.com/alauda/captain/assets/38375081/e39fbe7a-44cd-438b-9c9a-7e16a6fe567c)

日志提示“failed pre-install: timed out waiting for the condition”，是有什么条件不满足吗？还是其他什么问题

**Comment by zhhray** [comment]
"failed pre-install: timed out waiting for the condition" 意味着，在你的chart里存在了一个pre-install的hook，但是在安装chart时，这个hook没有执行成功，导致chart没能安装成功。
可以参考helm官方文档，了解hook的定义和原理。
一般这种hook应该是一个k8s的job资源，你需要排查对应的job为什么执行失败，并解决掉问题使得hook能正常运行。
从而继续使用Helmrequest安装这个chart。
