### ISSUE TITLE
what do they mean in release:chartData、configData、hooksData、manifestData

### ISSUE THREAD

**Issue by pangbin0502** [alauda/captain#95]
what do they mean in release:chartData、configData、hooksData、manifestData

**Comment by hangyan** [comment]
@zhhray We need a doc update to explain these data structures. Normally this Release object is on for internal use, so no document about them before. But still need to add this in the next updates.

**Comment by zhhray** [comment]
> what do they mean in release:chartData、configData、hooksData、manifestData

@pangbin0502 Please refer to the relevant PR commit, thx.

**Comment by pangbin0502** [comment]
thx
