### ISSUE TITLE
use harbor for helm server 

### ISSUE THREAD

**Issue by kanouken** [alauda/captain#97]
Warning  FailedSync  33s                 captain  chartrepos.app.alauda.io "harbor_chart" not found

  how to fix it ?

**Comment by hangyan** [comment]
You need to create a ChartRepo resource to represent the helm repo, checkout the docs about crd

**Comment by kanouken** [comment]
> You need to create a ChartRepo resource to represent the helm repo, checkout the docs about crd

it works now  ,Thanks
