### ISSUE TITLE
create HelmRequest error

### ISSUE THREAD

**Issue by 51qzpw** [alauda/captain#98]
captain-controller-manager: 1.3.1
描述： 我按照 README.md 中描述的方式安装，以及 替换默认的 helmrepo 仓库地址为 https://charts.bitnami.com/bitnami
根据 captain-controller-manager 的日志中可以看到 同步 https://charts.bitnami.com/bitnami 下面的 helm repo 都成功了；但是有以条日志一直在 间隔时间出现 “W0712 05:24:29.042097 1 info.go:62] no cluster found:the server could not find the requested resource (get clusters.clusterregistry.k8s.io)
W0712 05:24:29.042175 1 cluster.go:33] No cluster crd found, disable multi cluster supportthe server could not find the requested resource (get clusters.clusterregistry.k8s.io)”
当我安装 你们提供的示例文件去安装  nginx 的时候 出现失败
提示：'parse error at (nginx/charts/common/templates/_secrets.tpl:84): function
      "lookup" not defined'
    我还需要怎么做才可以消除 这个错误
！谢谢

**Comment by zhhray** [comment]
1. Captain support deploy chart to multiple clusters, but it depends on the `clusters.clusterregistry.k8s.io`. See here for detail https://github.com/kubernetes-retired/cluster-registry.
2. function "lookup" not defined'. Because the `lookup` function is used in the chart being deployed.But it is not supported by the lower Helm version referenced in Captain. We plan to upgrade helm dependency library  in the near future.

**Comment by 51qzpw** [comment]
@zhhray 好的，谢谢！ 我理解 第一个问题 “clusters.clusterregistry.k8s.io” 这个功能在不配置 多集群部署的情况下是不影响使用的对吗(但集群在不处理这个错误的情况下依然可以使用)
关于第二个 helm client 目前有其他办法可以绕开吗？ 我想试试 captain-controller 的功能

**Comment by zhhray** [comment]
> @zhhray 好的，谢谢！ 我理解 第一个问题 “clusters.clusterregistry.k8s.io” 这个功能在不配置 多集群部署的情况下是不影响使用的对吗(但集群在不处理这个错误的情况下依然可以使用)
> 关于第二个 helm client 目前有其他办法可以绕开吗？ 我想试试 captain-controller 的功能

1. Yes, it is not affected to use captain if multiple clusters are not configured.
2. Sorry, there is currently no better way to around this. unless you don't include a function such as `lookup` in your chart.

**Comment by wchajl** [comment]
请问计划在什么时候更新helm版本？我们现在也遇到了无法用 toRawJson函数的问题

**Comment by zhhray** [comment]
> 请问计划在什么时候更新helm版本？我们现在也遇到了无法用 toRawJson函数的问题

Ok, we will arrange a release as soon as possible to upgrade the helm version (at least 3.5+). Strive to be at the end of July or early August.

**Comment by zhhray** [comment]
I think the issue has been solved and will close it.
